declare const _default: {
    RUNEPOUCH_RUNE: number;
    XPDROP_COLORS: number;
    FRIENDS_CHAT_RANK_ICONS: number;
    PETS: number;
    POH_COSTUME_MEMBERS: number;
    POH_COSTUME_WARDROBE: number;
    POH_COSTUME_ARMOUR_CASE: number;
    POH_CAPE_RACK: number;
    POH_TOY_BOX: number;
    POH_COSTUME_CLUE_BEGINNER: number;
    POH_COSTUME_CLUE_EASY: number;
    POH_COSTUME_CLUE_MEDIUM: number;
    POH_COSTUME_CLUE_HARD: number;
    POH_COSTUME_CLUE_ELITE: number;
    POH_COSTUME_CLUE_MASTER: number;
    POH_COSTUME_ALTERNATE: number;
    POH_COSTUME_ALTERNATES: number;
    CLAN_RANK_NAME: number;
    CLAN_RANK_GRAPHIC: number;
    PRAYERS_NORMAL: number;
    PRAYERS_RUINOUS: number;
    PRAYERS_NORMAL_DEADEYE: number;
    PRAYERS_NORMAL_MYSTIC_VIGOUR: number;
    PRAYERS_NORMAL_DEADEYE_MYSTIC_VIGOUR: number;
    WORLD_LOCATIONS: number;
    WEAPON_STYLES: number;
    SPELLBOOKS: number;
    SPELLBOOKS_SUB: number;
    POTIONSTORE_POTIONS: number;
    POTIONSTORE_UNFINISHED_POTIONS: number;
};
export default _default;
